; host.ini
[testServer]
BROKER_HOST = 172.25.199.66
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = testExchange
QUEUE = testQueue
ROUTING_KEY = *
EXCHANGE_TYPE = topic
AUTO_DELETE = true

[errorQueue]
BROKER_HOST = 172.25.199.66
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = logExchange
QUEUE = errorQueue
ROUTING_KEY = *
EXCHANGE_TYPE = topic
AUTO_DELETE = true

[deployment]
BROKER_HOST = 172.25.199.66
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
QUEUE = deployment